<div class="heading-container">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper">
            <?php echo $this->getCurrentLock()->getName() ?>

        </span>
        <span class="base2" data-ui-id="page-title-wrapper">

            <?php echo $this->getCurrentLock()->getName2() ?>

        </span>
    </h1>
    <?php if($this->getImageLock()->getLogo()):?>
        <img class="lock-logo" src="<?php echo $this->getBaseUrl(). 'pub/media/' .  $this->getImageLock()->getLogo() ?>"/>
    <?php endif ?>
</div>

<div class="region-and-district">
    <span class="district"><?php echo __("District: ").$this->getDistrictName();?></span>
    <span> | </span>
    <span class="region"><?php echo __("Region: ").$this->getRegionName();?></span>
</div>
<div class="left-container">
    <div class="basic-info-container">
        <h3 class="detail-title"><?php echo __("Basic Infomation") ?></h3>
        <table class="basic-info">
            <?php if($this->getCurrentLock()->getAddress()):?>
                <tr>
                    <td> <?php echo __("Address:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getAddress(); ?> </td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getYear()):?>
                <tr>
                    <td> <?php echo __("Date of tenancy:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getYear(); ?> </td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getDeveloper()):?>
                <tr>
                    <td> <?php echo __("Developer:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getDeveloper(); ?> </td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getBlock()):?>
                <tr>
                    <td> <?php echo __("Block:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getBlock(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getHeight()):?>
                <tr>
                    <td> <?php echo __("Ceiling Height:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getHeight(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getPhrase()):?>
                <tr>
                    <td> <?php echo __("Phrase:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getPhrase(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getUnit()):?>
                <tr>
                    <td> <?php echo __("No. of units:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getUnit(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getUnitPerFloor()):?>
                <tr>
                    <td> <?php echo __("No. of units on each floor:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getUnitPerFloor(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getSize()):?>
                <tr>
                    <td> <?php echo __("Size:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getSize(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getBrand()):?>
                <tr>
                    <td> <?php echo __("Brand of lock:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getBrand(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getTypeOfLock()):?>
                <tr>
                    <td> <?php echo __("Type of lock:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getTypeOfLock(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getThickness()):?>
                <tr>
                    <td> <?php echo __("Door thickness:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getThickness(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getBackset()):?>
                <tr>
                    <td> <?php echo __("Backset:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getBackset(); ?></td>
                </tr>
            <?php endif ?>
        </table>
    </div>
    <div class="recommendation-container">
        <table class="recommendation">
            <?php if($this->getCurrentLock()->getLockset()||$this->getCurrentLock()->getCylinder()):?>
                <h3 class="detail-title"><?php echo __("Lock replacement recommendation") ?></h3>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getLockset()):?>
                <tr>
                    <td> <?php echo __("Lockset:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getLockset(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getCylinder()):?>
                <tr>
                    <td> <?php echo __("Cylinder:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getCylinder(); ?></td>
                </tr>
            <?php endif ?>
            <?php if($this->getCurrentLock()->getRemarks()):?>
                <tr>
                    <td> <?php echo __("Remarks:") ?> </td>
                    <td> <?php echo $this->getCurrentLock()->getRemarks(); ?></td>
                </tr>
            <?php endif ?>
        </table>
    </div>
    <div class="button-container">
        <a href="<?= $this->getBackUrl() ?>">
            <span class="back-button"> <?= __("BACK") ?>  </span>
        </a>

        <?php if($this->getProductUrl()):?>
            <a href="<?= $this->getProductUrl() ?>"><span> <?= __("GO TO PRODUCT DETAILS") ?> </span></a>
        <?php endif; ?>
    </div>
</div>




<div class="image-total-container">
    <div>
        <?php if($this->getImageLock()->getBeforeImage1()||$this->getImageLock()->getBeforeImage2()):?>
            <h3 class="img-hading"><?php echo __("Before Installation") ?></h3>
        <?php endif ?>
    <?php if($this->getImageLock()->getBeforeImage1()):?>
        <a class="img-wrapper" href="<?php echo $this->getBaseUrl(). 'pub/media/' . $this->getImageLock()->getBeforeImage1() ?>">
            <img class="before-img" src="<?php echo $this->getBaseUrl(). 'pub/media/' . $this->getImageLock()->getBeforeImage1() ?>"/>
        </a>
    <?php endif ?>

    <?php if($this->getImageLock()->getBeforeImage2()):?>
        <a class="img-wrapper" href="<?php echo $this->getBaseUrl(). 'pub/media/' . $this->getImageLock()->getBeforeImage2() ?>">
            <img class="before-img" src="<?php echo $this->getBaseUrl(). 'pub/media/' . $this->getImageLock()->getBeforeImage2() ?>"/>
        </a>
    <?php endif ?>
    </div>
    <div>
        <?php if($this->getCurrentLock()->getAfterImage1()||$this->getImageLock()->getAfterImage2()):?>
            <h3 class="img-hading"><?php echo __("After Installation") ?></h3>
        <?php endif ?>
    <?php if($this->getImageLock()->getAfterImage1()):?>
        <a class="img-wrapper" href="<?php echo $this->getBaseUrl(). 'pub/media/' .  $this->getImageLock()->getAfterImage1() ?>">
            <img class="before-img" src="<?php echo $this->getBaseUrl(). 'pub/media/' .  $this->getImageLock()->getAfterImage1() ?>"/>
        </a>
    <?php endif ?>

    <?php if($this->getImageLock()->getAfterImage2()):?>
        <a class="img-wrapper" href="<?php echo $this->getBaseUrl(). 'pub/media/' . $this->getImageLock()->getAfterImage2() ?>">
            <img class="after-img" src="<?php echo $this->getBaseUrl() . 'pub/media/' . $this->getImageLock()->getAfterImage2() ?>"/>
        </a>
    <?php endif ?>
    </div>
</div>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<div class="add-this-container"
     style="padding: 15px 0; margin-top: 30px;"
>
    <div class="add-this-text"
         style="    display: inline-block; font-size: 20px;"
    ><?php echo __("Share On") ?></div>
    <div class="addthis_sharing_toolbox"
         style="display: inline-block;margin-left: 20px;vertical-align: middle;"
    ></div>
</div>


<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-579b3dade41f4384"></script>
