<?php
$regions = $this->getRegionList();
$districtsArr = [];
?>
<div class="keyword-wrapper" style="">
    <div class="keyword-container">
        <input name="keyword" placeholder="<?php echo __('Please enter Property name / Address / Lock brands ...') ?>" />
    </div>
    <div style="float: none;clear: both;"></div>
</div>
<div class="red-line-container">
    <div class="red-line">
        <div class="lock-filter">
            <div class="district-filter left">
                <div class="filter-label">
                    <span><?php echo __('Region') ?></span>
                </div>
                <div class="filter-options-container">
                    <ul class="filter-checkboxs-list">
                        <li>
                            <input id="region_0" type="radio" name="region[]" value="" checked/><label for="region_0" class="active"><?php echo __('All') ?></label>
                        </li>
                        <?php foreach($regions as $region): ?>
                        <li>
                            <input id="region_<?php echo $region->getId() ?>" type="radio" name="region[]" value="<?php echo $region->getId() ?>" /><label for="region_<?php echo $region->getId() ?>"><?php echo $region->getName() ?></label>
                            <?php $districts = $this->getDistrictList($region); ?>
                            <?php if(!empty((array)$districts)): ?>
                            <?php
                                $district_shown_num = 0;

                                foreach($districts as $district) {
                                    $districtsArr[] = array('id'=>$district->getId(),'name'=>$district->getName());
                                }
                            ?>

                                <!--<select name="district_<?php /*echo $region->getId() */?>">
                                    <?php /*foreach($districts as $district): */?>

                                    <option value="<?php /*echo $district->getId() */?>"><?php /*echo $district->getName() */?></option>

                                    <?php /*endforeach; */?>
                                </select>-->

                            <?php endif; ?>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <div class="district-filter right">
                <!--<div class="filter-label">
                    <span><?php /*echo __('District') */?></span>
                </div>-->
                <div class="filter-options-container">
                    <?php $brands = $this->getBrandList(); ?>
                    <select name="district">
                        <option value=""><?php echo __('Show All (District)') ?></option>
                        <?php foreach($districtsArr as $district): ?>
                        <option value="<?php echo $district['id'] ?>"><?php echo $district['name'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="lock-list-container">
    <ul class="region-list">
        <?php foreach($regions as $region): ?>
        <?php $districts = $this->getDistrictList($region); ?>
        <?php $lock_num = $this->getLockCount($region) ?>
        <?php if(!empty((array)$districts) && $lock_num > 0): ?>
        <li class="region-item">
            <!--<h2 class="region-name">
                <?php /*echo $region->getName() */?>
            </h2>-->

            <ul class="district-list">

                <table class="lock-list">
                <?php foreach($districts as $district): ?>
                <?php $locks = $this->getLockList($district); ?>
                <?php if(!empty((array)$locks)): ?>

                    <tr class="district-name">
                        <td colspan="3"><?php echo $district->getName() ?></td>
                    </tr>

                    <?php foreach($locks as $lock): ?>

                            <tr class="lock-item">
                                <td class="lock-name"><a href="finder/view/identifier/<?php echo urlencode($lock->getIdentifier()) ?>"> <?php echo $lock->getName() ?> </a></td>
                                <td class="lock-name">
                                    <a href="finder/view/identifier/<?php echo urlencode($lock->getIdentifier())?>"> <?php echo $lock->getName2() ?> </a>
                                </td>
                                <td class="lock-name">
                                    <a href="finder/view/identifier/<?php echo urlencode($lock->getIdentifier())?>"><?php echo $lock->getAddress() ?>   </a>
                                </td>
                            </tr>

                    <?php endforeach; ?>
                <?php endif; ?>
                <?php endforeach; ?>

                </table>
            </ul>
        </li>
        <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>


<script>
    require([
        'jquery',
        'tabs'], function ($) {
        $(".district-filter ").find('.filter-label').click(function () {
            if($(window).width() < 768){
                $('.filter-checkboxs-list').slideToggle();
            }

        });

        $('.filter-checkboxs-list').find('input:radio').change(
            function(){
                $('.filter-checkboxs-list').find('label').removeClass('active');
                $(this).next().addClass('active');
            }
        );

    });
</script>