<?php
    $IncCapData = null;
    if((int)$this->getIncCapStatus('IncCapStatus') == 1){
        $IncCapData = $this->getIncCapData("IncCapData");
    }
?>
<div id="formTotalContainer" style="margin:0 auto; ">
    <div  border="0" align="center" cellpadding="0" cellspacing="0">
       <form class="form contact"
             action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
              id="registerForm"
              method="post"
              data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}'>

            <fieldset class="fieldset">

                    <div  border="0" cellpadding="0" cellspacing="0" class="regisdivation-form-info">
                        <h2 class="heading">
                            <div  valign="top" class="div-head"><div class="regisdivation-form-title"><?php echo __('Customer Information'); ?></div></div>
                            <div  valign="top">&nbsp;</div>
                        </h2>

                        <div>
                            <!--<div valign="top"><div align="right"><img src="ssl.jpg"/></div></div>-->
                        </div>
                        <div>
                            <div class="dt"><font id="salu_sp" >*<?php echo __('Salutation') ?></font></div>
                            <div class="dd">
                                    <input type="radio" class="radio" id="bundle-option-3-5" data-validate="{'validate-one-required-by-name':true}" name="salutation" value="Mr" <?php if ($IncCapData['salutation'] == 'Mr') {echo 'checked';} ?> />
                                    <label class="label" for="bundle-option-3-5">
                                        <?php echo __('Mr'); ?>
                                    </label>
                                    <input type="radio" class="radio" id="bundle-option-3-6" data-validate="{'validate-one-required-by-name':true}" name="salutation" value="Mrs" <?php if ($IncCapData['salutation'] == 'Mrs') {echo 'checked';} ?> />
                                    <label class="label" for="bundle-option-3-6">
                                        <?php echo __('Mrs'); ?>
                                    </label>
                                    <input type="radio" class="radio" id="bundle-option-3-7" data-validate="{'validate-one-required-by-name':true}" name="salutation" value="Miss" <?php if ($IncCapData['salutation'] == 'Miss') {echo 'checked';} ?> />
                                    <label class="label" for="bundle-option-3-7">
                                        <?php echo __('Miss'); ?>
                                    </label>
                            </div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                            
                            <div class="dt"><font id="fname_sp" >*<?php echo __('English First Name') ?></font></div>
                            <div class="dd"><input type="text" name="eng_first_name" maxlength="50" class="fieldWidth" data-validate="{required:true}" aria-required="true"  data-validate="{required:true}" aria-required="true" value="<?php echo $IncCapData['eng_first_name'];?>"/></div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                            
                            <div class="dt"><font id="lname_sp" >*<?php echo __('English Last Name') ?></font></div>
                            <div class="dd"><input type="text" name="eng_last_name" maxlength="50" class="fieldWidth" data-validate="{required:true}" aria-required="true"  value="<?php echo $IncCapData['eng_last_name'];?>"/></div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                            <div class="dt" id="cname_div" >&nbsp;<?php echo __('Chinese Name (if applicable)') ?></div>
                            <div class="dd"><input type="text" name="chi_name" maxlength="25" class="fieldWidth"  value="<?php echo $IncCapData['chi_name'];?>"/></div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                            
                            <div class="dt">&nbsp;<?php echo __('Company Name (if applicable)') ?></div>
                            <div class="dd"><input type="text" name="company" maxlength="100" class="fieldWidth" value="<?php echo $IncCapData['company'];?>"/></div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>

                        <script>
                            function changeID() {
                                var x = document.getElementById("isHKID").value;
                                if(x == 1){
                                    document.getElementById("hkid").style.display = 'block';
                                    document.getElementById("pport").style.display = 'none';
                                    document.getElementById("pport").childNodes[1].value = '';
                                    document.getElementById("hkid").childNodes[1].value = '';
                                }else if(x == 2) {
                                    document.getElementById("hkid").style.display = 'none';
                                    document.getElementById("hkid").childNodes[1].value = '';
                                    document.getElementById("pport").childNodes[1].value = '';
                                    document.getElementById("pport").style.display = 'block';
                                }
                            }
                            require([
                                'jquery', // jquery Library
                                'jquery/ui', // Jquery UI Library
                                'jquery/validate', // Jquery Validation Library
                                'mage/translate' // Magento text translate (Validation message translte as per language)
                            ], function($){
                                $.validator.addMethod(
                                    'validate-hkid-passport', function (v,elm) {
                                        var inputs = $('.id-num');

                                        var error = 1;
                                        for(var i=0;i<inputs.length;i++) {
                                            if(inputs[i].type == 'text'  && inputs[i].value !== "") {
                                                error = 0;
                                                if( i == 0 && inputs[i].value.length<4){
                                                    error =1;
                                                }
                                            }
                                        }

                                        if( error == 0 ) {
                                            return true;
                                        } else {
                                            return false;
                                        }

                                    }, "<?php  echo __('Enter Valid HKID/Passport Number') ?>" );

                            });
                        </script>

                        <div>
                            <div valign="top" class="dt"><font id="id_sp" >
                                    *<?php echo __('Hong Kong ID / Passport or<br>&nbsp;other ID') ?></font></div>
                            <div class="dd">
                                <select name="isHKID" id="isHKID" onChange="changeID()" data-validate="{required:true}" aria-required="true" >
                                    <option value="1" <?php if($IncCapData['isHKID']=='1'){ print 'selected'; }?> ><?php echo __('HKID')?></option>
                                    <option value="2" <?php if($IncCapData['isHKID']=='2'){ print 'selected'; }?> ><?php echo __("Passport or other ID")?></option>
                                </select><br>

                                <div id="hkid" style="<?php if($IncCapData['isHKID']=='1' || $IncCapData['isHKID'] == NULL ){ print 'display:block'; } else {print  'display:none';}?>">
                                    <input type="text" name="hkid" class="text id-num" data-validate="{'validate-hkid-passport':true}" maxlength="4" size="1" value="<?php echo $IncCapData['hkid'];?>"/>
                                    A123&nbsp;<br><?php echo __('first 4 digit, including the first letter)')?></div>


                                <div id="pport" style="<?php if($IncCapData['isHKID']=='2' ){ print 'display:block'; } else {print  'display:none';}?>">
                                    <input type="text" name="passport_num" class="text id-num"  data-validate="{'validate-hkid-passport':true}" maxlength="20" class="fieldWidth" value="<?php echo $IncCapData['passport_num'];?>"/>
                                </div>

                                </div>
                        </div>


                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                            
                            <div valign="top" class="dt"><font id="contact_sp" >
                                    <?php echo __('*Contact No. (1)') ?></font></div>
                            <div class="dd">
                                <div cellpadding="0" cellspacing="0" border="0" class="fieldWidth" data-validate="{required:true}" aria-required="true" >
                                    <div>
                                        <!--<div><input type="text" name="areaCode1" maxlength="5" size="3" value="86"/></div>
                      <div>&nbsp;-&nbsp;</div>  -->
                                        <div class="country-code">
                                            <input type="text" name="contact_one_country_code" maxlength="4" size="4" value="852" class="fieldWidth" data-validate="{required:true}" aria-required="true" /></div>
                                        <div class="separate"align="center">-</div>
                                        <div class="tel"><input type="text" name="contact_one_phone" maxlength="20" size="14" class="fieldWidth" data-validate="{'validate-digits':true}" aria-required="true" value="<?php echo $IncCapData['contact_one_phone'];?>"/></div>
                                    </div>
                                    <div>
                                        <!--<div id="contact1_ac" style="font-size:10px">(Area Code)</div>
                      <div>&nbsp;-&nbsp;</div>  -->
                                        <div id="contact1_cc" class="country-code" style="font-size:10px;">
                                            (<?php echo __('Coundivy Code')?>)</div>
                                        <div align="center" class="separate">-</div>
                                        <div id="contact1_no" class="tel" style="font-size:10px;">
                                            (<?php echo __('Number');?>)</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                           
                            <div valign="top" class="dt" id="contact2_div" >
                                &nbsp;<?php echo __('Contact No. (2)') ?></div>
                            <div class="dd">
                                <div cellpadding="0" cellspacing="0" border="0" class="fieldWidth" data-validate="{required:true}" aria-required="true" >
                                    <div>
                                        <!--<div><input type="text" name="areaCode2" maxlength="5" size="3" value="86" value=""/></div>
                      <div>&nbsp;-&nbsp;</div>  -->
                                        <div class="country-code">
                                            <input type="text" name="contact_two_country_code" maxlength="4" size="4" value="852"/></div>
                                        <div class="separate" align="center">-</div>
                                        <div class="tel"><input type="text" name="contact_two_phone" data-validate="{'validate-digits':true}" maxlength="20" size="14" value="<?php echo $IncCapData['contact_two_phone'];?>"/></div>
                                    </div>
                                    <div>
                                        <!--<div id="contact2_ac" style="font-size:10px">(Area Code)</div>
                      <div>&nbsp;-&nbsp;</div>  -->
                                        <div id="contact1_cc" class="country-code" style="font-size:10px;">
                                            (<?php echo __('Coundivy Code')?>)</div>
                                        <div align="center" class="separate">-</div>
                                        <div id="contact1_no" class="tel" style="font-size:10px;">
                                            (<?php echo __('Number');?>)</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                            <div valign="top" class="dt" id="email_div" >&nbsp;<?php echo __('E-mail Address') ?></div>
                            <div class="dd">
                                <input type="text" name="email" maxlength="60" class="fieldWidth" data-validate="{'validate-email':true}"  aria-required="true"  value="<?php echo $IncCapData['email'];?>" required/>
                                <p class="fieldWidth" data-validate="{'validate-email':true}" aria-required="true"  style="font-size:10px">
                                    <?php echo __('A copy of this regisdivationform will be sent to the e-mail address provided for reference.');?>
                                </p>
                            </div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                            <div class="dt" id="sq_div" >*<?php echo __('Security question') ?></div>
                            <div class="dd">
                                <select name="question_type" id="sQuest" class="fieldWidth" data-validate="{'validate-select':true}" aria-required="true" >
                                    <option value="none" <?php if($IncCapData['question_type']=='none'){ print 'selected'; }?>><?php echo __('Select One')?></option>
                                    <option value="1" <?php if($IncCapData['question_type']=='1'){ print 'selected'; }?>><?php echo __('Who is your favourite singer?');?></option>
                                    <option value="2" <?php if($IncCapData['question_type']=='2'){ print 'selected'; }?>><?php echo __('What is your favourite pastime?');?></option>
                                    <option value="3" <?php if($IncCapData['question_type']=='3'){ print 'selected'; }?>><?php echo __('What is your favourite sports team?');?></option>
                                    <option value="4" <?php if($IncCapData['question_type']=='4'){ print 'selected'; }?>><?php echo __('What is the name of your primary school?');?></option>
                                    <option value="5" <?php if($IncCapData['question_type']=='5'){ print 'selected'; }?>><?php echo __("What is your pet's name?");?></option>
                                    <option value="6" <?php if($IncCapData['question_type']=='6'){ print 'selected'; }?>><?php echo __('What colour do you like best?');?></option>
                                    <option value="7" <?php if($IncCapData['question_type']=='7'){ print 'selected'; }?>><?php echo __('Which is your favourite festival?');?></option>
                                    <option value="8" <?php if($IncCapData['question_type']=='8'){ print 'selected'; }?>><?php echo __('What is your favourite fruit?');?></option>
                                </select>
                            </div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>

                        <div>
                            <div class="dt"><font id="sAnswer_sp" >*<?php echo __('Your answer') ?></font></div>
                            <div class="dd">
                                <input type="text" name="answer" id="sAnswer" maxlength="30" class="fieldWidth" data-validate="{required:true}" aria-required="true"  value="<?php echo $IncCapData['answer'];?>"/>
                            </div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>

                        <div>
                            <div class="dt">
                                <font id="dealer_sp" >*<?php echo __('Date of Birth') ?></font></div>
                            <div class="dd">
                                <input type="text" class="date-pick" readonly='true' name="date_of_birth" maxlength="20" data-validate="{'validate-date':true, 'required-entry':true}" class="fieldWidth"  autocomplete="off" value="<?php echo $IncCapData['date_of_birth'];?>"/>
                            </div>
                        </div>

                        <div>
                            
                            <div>&nbsp;</div>
                            <div>&nbsp;</div>
                        </div>
                        <div>
                            
                            <div>&nbsp;</div>
                            <div>&nbsp;</div>
                        </div>
                        <h2  class="heading">
                            <div class="div-head"><div class="regisdivation-form-title"><?php echo __('Product Information'); ?></div></div>
                            <div  valign="top">&nbsp;</div>
                        </h2>
                        <div>
                            <div class="dt"><font id="brandTitle" >*<?php echo __('Brand') ?></font></div>
                            <div class="dd">
                                <input type="text" name="brand" id="brand" maxlength="30" class="fieldWidth" data-validate="{required:true}" aria-required="true"  value="Mul-T-Lock MT5" readonly/>
                            </div>
                        </div>
                        <div>
                           <div class="dt" id="pc_div" >
                                *<?php echo __('Product Category') ?></div>
                            <div class="dd">
                                <select name="product_type" class="fieldWidth" data-validate="{'validate-select':true}" aria-required="true" >
                                    <option value="none" <?php if($IncCapData['product_type']=='none'){ print 'selected'; }?>><?php echo __("Select One");?></option>
                                    <option value="1" <?php if($IncCapData['product_type']=='1'){ print 'selected'; }?>><?php echo __("Auxiliary Lock");?></option>
                                    <option value="2" <?php if($IncCapData['product_type']=='2'){ print 'selected'; }?>><?php echo __("Cylinder");?></option>
                                    <option value="3" <?php if($IncCapData['product_type']=='3'){ print 'selected'; }?>><?php echo __("Endivance Lockset");?></option>
                                    <option value="4" <?php if($IncCapData['product_type']=='4'){ print 'selected'; }?>><?php echo __("Others");?></option>
                                </select>
                            </div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div bgcolor="#FFFFFF">
                            <div valign="top" class="dt"><font id="keyInfo_sp" >
                                    *<?php echo __('Keycard Information'); ?></font></div>
                            <div class="dd">
                                <div cellpadding="0" cellspacing="2" border="0">
                                    <div>
                                        <div width="110"><font id="sn_sp" color="#9999CC" size="-2">
                                                <b>1. <?php echo __("Serial Number")?></b></font></div>
                                        <div><input style="" name="serial_num" type="text" maxlength="5" class="fieldWidth" data-validate="{required:true}" aria-required="true"  value="<?php echo $IncCapData['serial_num'];?>"/></div>
                                    </div>
                                    <div>
                                        <div><font id="pn_sp" color="#9999CC" size="-2">
                                                <b>2. <?php echo __("Profile")?></b></font></div>
                                        <div><input style="" name="profile" type="text" maxlength="4" class="fieldWidth" data-validate="{required:true}" aria-required="true"  value="<?php echo $IncCapData['profile'];?>"/></div>
                                    </div>
                                    <div>
                                        <div><font id="pins_sp" color="#9999CC" size="-2">
                                                <b><?php echo __("3. T-Combination")?></b></font></div>
                                        <div><input style="" name="t_combination" type="text" maxlength="10" class="fieldWidth" data-validate="{required:true}" aria-required="true"  value="<?php echo $IncCapData['t_combination'];?>"/></div>
                                    </div>
                                    <div>
                                        <div><font id="snake_sp" color="#9999CC" size="-2">
                                                <b><?php echo __("4. FP-Combination")?></b></font></div>
                                        <div><input style="" name="fp_combination" type="text" maxlength="5" class="fieldWidth" data-validate="{required:true}" aria-required="true"  value="<?php echo $IncCapData['fp_combination'];?>"/></div>
                                    </div>
                                </div>
                                <!--<div id="keyTable" width="500" height="300"cellpadding="0" cellspacing="0" border="0" background="mul_t.jpg">
                  <div>
                  <div height="100%"></div>
                  </div>
                  </div>-->
                                <!-- <font size="-2">Width: 500px,&nbsp;&nbsp;&nbsp;&nbsp;Height:300px</font>-->
                            </div>
                        </div>
                        <div>
                            
                            <div class="dt">&nbsp;</div>
                            <div class="dd">&nbsp;</div>
                        </div>
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mt5_form_img_en')->toHtml();?>
                        <div>

                            <div>&nbsp;</div>
                            <div>&nbsp;</div>
                        </div>
                        <h2  class="heading">
                            <div class="div-head"><div class="regisdivation-form-title"><?php echo __('Purchase Information'); ?></div></div>
                            <div  valign="top">&nbsp;</div>
                        </h2>

                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                            
                            <div class="dt">
                                <font id="dealer_sp" >*<?php echo __('Date'); ?></font></div>
                            <div class="dd">
                                <input type="text" class="date-pick" value="<?php echo $IncCapData['date_of_purchase'];?>" readonly='true' name="date_of_purchase" data-validate="{'validate-date':true, 'required-entry':true}" maxlength="20" class="fieldWidth"  autocomplete="off" />
                            </div>
                        </div>
                        <div>

                            <div class="dt">
                                <font id="dealer_sp" >*<?php echo __('Name of Dealer')?></font></div>
                            <div class="dd">
                                <input type="text" name="name_of_dealer" maxlength="50" class="fieldWidth" data-validate="{required:true}" aria-required="true"  value="<?php echo $IncCapData['name_of_dealer'];?>"/>
                            </div>
                        </div>
                        <div>
                            
                            <div height="10"></div>
                            <div height="10"></div>
                        </div>
                        <div>
                            
                            <div class="dt">&nbsp;<?php echo __('Invoice No')?>.</div>
                            <div class="dd">
                                <input type="text" name="invoice_no" maxlength="20" class="fieldWidth" value="<?php echo $IncCapData['invoice_no'];?>" />
                            </div>
                        </div>
                        <script>
                            require([
                                "jquery",
                                "mage/calendar"
                            ], function($){
                                $(".date-pick").calendar({
                                    dateFormat: "yyyy-mm-dd",
                                    yearRange: "-100:+0",
                                    showsTime: false,
                                    changeMonth: true,
                                    changeYear: true,
                                    sideBySide: true,
                                    numberOfMonths: 1,
                                    closeText: "Done",
                                    selectOtherMonths: true,
                                    onClose: function( selectedDate ) {
                                        $( "#period_date_end" ).datepicker( "option", "minDate", selectedDate );
                                    }
                                });

                            });
                        </script>

                        <div>
                            
                            <div class="dt">&nbsp;</div>
                            <div class="dd">&nbsp;</div>
                        </div>
                    </div>
            </fieldset>
           <!-- Captcha -->
           <div class="warranty_cap">
               <?php echo $block->getChildHtml('warranty_captcha'); ?>
           </div>
            <div>
                <div colspan="2" align="center" height="60" valign="middle" bgcolor="#FFFFFF" class="btn-review">
                    <button type="submit" class="action submit primary regisdivation-agree">
                        <?php echo __('Review this form') ?>
                    </button>
                </div>
            </div> <!--submit btn-->
        </form>
    </div>