<?php
    /*@var */


/**
 * @var $block Cleargo\BrandList\Block\Listing
 */
    $attrSets = $block->getAllAttrSetId();
?>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brand_top_navigation')->toHtml();?>

<?php foreach ($attrSets as $attrSet): ?>
    <?php if($attrSet['value'] != '4'): ?>
        <ul class="brands_list" id="brandList<?php echo $attrSet['value']; ?>">
            <h2> <?php echo __($attrSet['label']); ?> </h2>
            <?php foreach(range('A','Z') as $i): ?>

                <?php
                $allBrands = $block->getAllBrandByAttrSet($attrSet['value']);

                $isDisplay = false;
                foreach ($allBrands as $brand){
                    if( $brand['group'] == $i) $isDisplay = true;
                }
                ?>

                <?php if($isDisplay):?>
                    <li> <h2><?php echo __($i) ?></h2>
                <?php endif; ?>

                <?php foreach ($allBrands as $brand):?>
                    <?php if( $brand['group'] == $i):?>
                        <p>
                            <a href="
                   /catalogsearch/advanced/result/?name=&sku=&description=&short_description=&price%5Bfrom%5D=&price%5Bto%5D=&brand%5B%5D=<?php echo $brand['id'] ?>&features_specifications=&dimension=
                    "><?php echo $brand['label']; ?></a>
                        </p>
                    <?php endif; ?>
                <?php endforeach;?>

                <?php if($isDisplay):?>
                    </li>
                <?php endif; ?>

            <?php endforeach;?>
            <!--<li style="clear: both;"></li>-->
        </ul>
    <?php endif; ?>
<?php endforeach; ?>





