<?php $cur_cate_id =  $block->getCurrentCategory()->getId(); ?>
<?php if($block->canDisplay()): ?>
<?php foreach ($block->getEvents() as $_event): ?>
    <?php $_category = $_event->getCategory(); ?>
        <?php if($cur_cate_id == $_category->getId()): ?>
            <div class="block block-category-event <?php /* @escapeNotVerified */ echo $_event->getStatus()?>">
                <div class="block-title">
                    <strong>
                        <?php /* @escapeNotVerified */ echo $block->getStatusText($_event); ?>
                    </strong>
                </div>
                <div class="block-content">
                    <?php switch ($_event->getStatus()):
                        case \Magento\CatalogEvent\Model\Event::STATUS_UPCOMING: ?>
                            <div class="dates">
                                <div class="start">
                                    <span class="date"><?php /* @escapeNotVerified */ echo $block->getEventDate('start', $_event); ?></span>
                                    <span class="time"><?php /* @escapeNotVerified */ echo $block->getEventTime('start', $_event, 'hh a zzz'); ?></span>
                                </div>
                                <div class="end">
                                    <span class="date"><?php /* @escapeNotVerified */ echo $block->getEventDate('end', $_event); ?></span>
                                    <span class="time"><?php /* @escapeNotVerified */ echo $block->getEventTime('end', $_event, 'hh a zzz'); ?></span>
                                </div>
                            </div>
                            <?php break;
                        case \Magento\CatalogEvent\Model\Event::STATUS_OPEN: ?>

                            <ul class="ticker" id="event-ticker-<?php /* @escapeNotVerified */ echo $_event->getId() ?>"
                                data-mage-init='{"ticker":{"eventEndTimeUTC": <?php /* @escapeNotVerified */ echo $block->getEndTimeUTC($_event); ?>}}'>
                                <li class="days">
                                    <span data-container="days" class="value">&nbsp;</span>
                                    <span class="label"><?php /* @escapeNotVerified */ echo __('Days') ?></span>
                                </li>
                                <li class="hour">
                                    <span data-container="hour" class="value">&nbsp;</span>
                                    <span class="label"><?php /* @escapeNotVerified */ echo __('Hrs') ?></span>
                                </li>
                                <li class="minute">
                                    <span data-container="minute" class="value">&nbsp;</span>
                                    <span class="label"><?php /* @escapeNotVerified */ echo __('Mins') ?></span>
                                </li>
                                <li class="second">
                                    <span data-container="second" class="value">&nbsp;</span>
                                    <span class="label"><?php /* @escapeNotVerified */ echo __('Sec') ?></span>
                                </li>
                            </ul>
                            <?php break;
                        case \Magento\CatalogEvent\Model\Event::STATUS_CLOSED: ?>
                            <div class="dates">
                                <div class="start">
                                    <span class="date"><?php /* @escapeNotVerified */ echo $block->getEventDate('start', $_event); ?></span>
                                    <span class="time"><?php /* @escapeNotVerified */ echo $block->getEventTime('start', $_event, 'hh a zzz'); ?></span>
                                </div>
                                <div class="end">
                                    <span class="date"><?php /* @escapeNotVerified */ echo $block->getEventDate('end', $_event); ?></span>
                                    <span class="time"><?php /* @escapeNotVerified */ echo $block->getEventTime('end', $_event, 'hh a zzz'); ?></span>
                                </div>
                            </div>
                            <?php break; ?>
                        <?php endswitch; ?>
                </div>
            </div>
            <div class="category-info">
                <?php if ($block->getEventImageUrl($_event)): ?>
                    <img src="<?php /* @escapeNotVerified */ echo $block->getEventImageUrl($_event); ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>" alt="<?php echo $block->escapeHtml($_category->getName()) ?>" />
                <?php else: ?>
                    <span class="category-name"><?php echo $block->escapeHtml($_category->getName()) ?></span>
                <?php endif; ?>
            </div>
    <?php endif; ?>
<?php endforeach; ?>
<?php endif; ?>