<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$fullDataProduct = $objectManager->get('Magento\Catalog\Model\Product')->load($item->getProductId());
?>

<?php if(!$fullDataProduct->getIsShowOnly()):?>
    <?php foreach ($block->getChildNames() as $childName): ?>
        <?php /* @escapeNotVerified */ echo $block->getLayout()->renderElement($childName, false); ?>
    <?php endforeach;?>
<?php endif;?>


