<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>

    <button type="submit"
            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
            class="action primary tocart"
            id="product-updatecart-button">
        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
    </button>
    <?php echo $block->getChildHtml('', true) ?>
    
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
