<?php
/**
 * Strategery Infinitescroll - Magento 2 Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0),
 * available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @license http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @copyright Copyright (c) 2016 Strategery Inc. (http://www.strategery.io/)
 * @author Damian A. Pastorini (damian.pastorini@strategery.io)
 */
?>
<?php /** @var $block \Strategery\Infinitescroll\Block\Init */ ?>
<?php if ($block->isEnabled()) : ?>
    <?php
    $productListMode = $block->getProductListMode();
    $mode = ($productListMode == 'grid') ? $block->getSelector('items_grid') : $block->getSelector('items_list');
    ?>
    <script>
        window.iasConfig = {
            mode: '<?php echo $block->escapeHtml($mode); ?>',
            debug: <?php echo (int) $block->getScrollConfig('general/debug'); ?>,
            container: '<?php echo $block->escapeHtml($block->getSelector('content')); ?>',
            next: '<?php echo $block->escapeHtml($block->getSelector('next')); ?>',
            pagination: '<?php echo $block->escapeHtml($block->getSelector('pagination')); ?>',
            buffer: <?php echo (int) $block->getDesign('buffer_px'); ?>,
            prev: '<?php echo $block->escapeHtml($block->getSelector('previous')); ?>',
            text: '<?php echo $block->escapeJsQuote(__($block->getDesign('done_text'))); ?>',
            html: '<div class="ias-noneleft" style="text-align: center;">{text}</div>',
            <?php if ($block->getLoaderImage() !== false): ?>
            spinnerSrc: '<?php echo $block->escapeUrl($block->getLoaderImage()); ?>',
            <?php else: ?>
            spinnerSrc: '<?php echo $block->getViewFileUrl('Strategery_Infinitescroll::images/loader.gif'); ?>',
            <?php endif; ?>
            spinnerHtml: '<?php echo '<div class="ias-spinner" style="text-align: center;"><img style="display:inline" src="{src}"/> '.$block->escapeJsQuote(__($block->getScrollConfig('design/loading_text'))).'</div>'; ?>',
            trigger: {
                text: '<?php echo $block->escapeJsQuote(__($block->getDesign('load_more_text'))); ?>',
                html: '<div class="ias-trigger ias-trigger-next" style="text-align: center; cursor: pointer;"><a>{text}</a></div>',
                textPrev: '<?php echo $block->escapeJsQuote(__($block->getDesign('load_more_text_prev'))); ?>',
                htmlPrev: '<div class="ias-trigger ias-trigger-prev" style="text-align: center; cursor: pointer;"><a>{text}</a></div>',
                offset: <?php echo (int) $block->getDesign('load_more_threshold'); ?>
            },
            toolbarSelector: '<?php echo $block->escapeHtml($block->getSelector('toolbar')); ?>',
            toolbarAction: '<?php echo $block->getDesign('hide_toolbar') ? 'hide' : 'show'; ?>',
            memoryActive: <?php echo $block->isMemoryActive() ? 'true' : 'false'; ?>
        };
        require(['jquery', 'jqueryIas', 'infinitescroll'], function($){
            $(window).load(function() {
                // InfiniteScroll:
                console.log('testScroll');
                SgyIAS.init();
            });
        });
    </script>
<?php endif ?>
