<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */

//
// Source Clone from :
//      vendor/magento/module-catalog/view/frontend/templates/product/list/items.phtml
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Products you might like');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>

<?php if ($exist):?>

<?php if ($type == 'related' || $type == 'upsell'): ?>
    <?php if ($type == 'related'): ?>
        <div id="<?php /* @escapeNotVerified */ echo $class; ?>-product-slider" class="slider-outer" >
    
        <?php else: ?>
        <div id="<?php /* @escapeNotVerified */ echo $class; ?>-product-slider" class="slider-outer" >
        <?php endif; ?>
    <?php else: ?>
        <div id="<?php /* @escapeNotVerified */ echo $class; ?>-product-slider" class="slider-outer">
<?php endif; ?>
            <h2 class="title">
                <?php /* @escapeNotVerified */ //echo $title;
                $title = explode(" ",$title);
                for ($i = 0; $i < count($title); $i++) {
                    if($i>0){echo "<i> ";}
                    echo $title[$i];
                    if($i>0){echo "</i>";}
                }
                 ?>
            </h2>
            <div class="<?php echo $class; ?> slider_wrapper">
                <div class="slider-box">
                    <div id="<?php echo $class; ?>-left" class="slider-left"><img src="<?php echo $block->getViewFileUrl('images/slider_arrow_prev.png')?>" alt="<?php echo __('Previous')?>" /></div>
                    <div class="slider-canvas products-grid">
                        <ol class="slider" id="<?php echo $class; ?>-items">
                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?php $available = ''; ?>
                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <?php $available = 'related-available'; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($type == 'related' || $type == 'upsell'): ?>
                                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item">' : '</li><li class="item">' ?>
                                <?php else: ?>
                                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item">' : '</li><li class="item">' ?>
                                <?php endif; ?>
                                <div class="item-wrapper <?php /* @escapeNotVerified */ echo $available; ?>">
                                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="image">
                                        <?php //echo $block->getImage($_item, $image)->toHtml(); ?>
                                        <?php
                                        $imagehelper = $objectManager->create('Magento\Catalog\Helper\Image');
                                        $productImage = $imagehelper->init($_item, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(270,270)->getUrl();
                                        ?>
                                        <img src="<?php echo $productImage; ?>" alt="<?php echo $_item->getName()?>" />
                                    </a>
                                    <div class="info">
                                        <h4 class="name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                        </h4>

                                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                                    </div>
                                </div>
                                <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ol>
                    </div>
                    <div id="<?php echo $class; ?>-right" class="slider-right"><img src="<?php echo $block->getViewFileUrl('images/slider_arrow_next.png')?>" alt="<?php echo __('Previous')?>" /></div>
        
                </div>
            </div>
        </div>
<?php endif;?>