<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php $label_e = explode(" ",$label);
                        for ($i = 0; $i < count($label_e); $i++) {
                            if($i>0){echo "<i> ";}
                            echo $label_e[$i];
                            if($i>0){echo "</i>";}
                        }
                        ?>
                        
                        <?php /* @escapeNotVerified */ //echo $label; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<div class="add-this-container"
     style="border-top: 1px solid gainsboro; border-bottom: 1px solid gainsboro; padding: 15px 0;"
>
    <div class="add-this-text"
         style="    display: inline-block; font-size: 20px;margin-left: 15px;"
    ><?php echo __("Share On") ?></div>
    <div class="addthis_sharing_toolbox"
         style="display: inline-block;margin-left: 20px;vertical-align: middle;"
    ></div>
</div>


<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-579b3dade41f4384"></script>

<script type="text/javascript">
    var addthis_config = addthis_config||{};
    addthis_config.pubid = 'ra-579b3dade41f4384';
    addthis_config.ui_language = 'en';
</script>