<table class="pdf-container">


   <?php
        $pdfs =  $this->getPdfList();
   ?>

   <?php foreach ($pdfs as $pdf): ?>
       <tr>
           <td><img src="<?= $this->getMediaPrefix().'cleargo/product/pdf/icon_pdf-small.gif' ?>" /></td>
           <td><?= str_replace("cleargo/product/pdf","",$pdf['pdf_path'])  ?></td>
           <td><a href="<?= $this->getMediaPrefix().$pdf['pdf_path'] ?>"> <?= __('View') ?> </a> </td>
           <td><a href="<?= $this->getMediaPrefix().$pdf['pdf_path'] ?>"> <?= __('Download') ?> </a> </td>
       </tr>
   <?php endforeach; ?>




</table>