<?php

/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
$_postCollection = $block->getPostCollection();
foreach ($_postCollection as $value) {

}
?>


<h2><?php echo __("What's ") ?><i><?php echo __('News') ?></i></h2>
<div class="flexslider news-slide" style="margin: 0 20px;">
    <ul class="slides">

        <?php if ($_postCollection->count()): ?>
            <?php foreach ($_postCollection as $_post): ?>
                <?php
                $_postUrl = $_post->getPostUrl();
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                $cts = $_post->getParentCategories();

                ?>
                <li>
                    <div class="news-container" style="max-width: 450px; width: 100%; margin: 0 auto;">
                        <div class="news-content" style="text-align: left;
    font-size: initial;">
                            <?php if($_post->getFeaturedImage()): ?>
                                <img src="<?php echo $_post->getFeaturedImage(); ?>" />
                            <?php endif; ?>
                            <h4>
                                <a class="post-item-link"
                                   href="<?php echo $_postUrl ?>">
                                    <?php echo $_postName; ?>
                                </a>
                            </h4>
                            <span class="date"><?php echo $_post->getPublishDate('F d, Y') ?></span>
                            <div class="post-text-hld clearfix">
                                <?php echo $block->getShorContent($_post) ?>
                            </div>
                            <div>
                                <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>" >
                                    <?php echo __('Read more') ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        <?php endif; ?>
    </ul>
</div>